### ISSUE TITLE
Client-level Pop-ups

### ISSUE THREAD

**Issue by gwenbeebe** [abtassociates/DQ_CE#88]
If at all possible, it would be great to be able to click on the chart and get a pop-up with a list of the clients who have that error. I'm imagining clicking on this bar and seeing a new box with a table of the clients who need race information added. We wouldn't need a ton of information, maybe just `vars_we_want[c(5, 2, 7:10)]`?

![image](https://user-images.githubusercontent.com/119484824/206301812-7485fb66-9eba-4495-af21-b2c46f0363dc.png)

At least, if the hope is for folks to use Eva actively while working on their data. If they're just logging in, running everything, downloading the details, working off those excel files, then coming back later, it wouldn't matter!

**Comment by kiadso** [comment]
Hi @gwenbeebe <3
Thanks for the suggestion! Your last sentence is right though: since it is being written for the HMIS Admins/Leads, we didn't go super deep with functionality that an HMIS End User would find helpful. The most common use case for the Data Quality portion of this app, from the End User's perspective, will be their HMIS Lead running it for the whole system, then reviewing/editing the Organization-level exports and sending them on to the organizations that need to sort out their data issues. The End User would use that workbook to make their corrections.
Thanks again! :)
